### ISSUE TITLE
Video running behind sound (older Roku)

### ISSUE THREAD

**Issue by pixeljank** [bananaoomarang/bombermin#12]
Found that the app is currently pulling the best available video from GB which is causing older Rokus to play video out of sync with audio. This was a problem on the official app which was solved by limiting feeds to 720p. Suggest an option to limit video quality otherwise app will only be useable by latest devices. 

Thanks for developing the app so far!

**Comment by bananaoomarang** [comment]
Hey sorry... Only just saw this for some reason. Sounds like this should be a fairly simple fix so should be able to get to it soon. I think I can add an option to limit video quality for older devices...

**Comment by bananaoomarang** [comment]
OK @pixeljank this should be 'fixed' now. Just pushed an update (1.5.0) that gives users an option to select video quality.

You should be able to choose `FHD`, `HD` and `SD`, by default it should land on `HD` (previously it was `FHD` and not customizable)
